TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += controls.db
DATA += lv_controls.xml

#=======================================
include $(TOP)/configure/RULES
